# もし dataset, dataset.subset に同名オプションの記述があった場合にはそちらが優先される
[general]
shuffle_caption = true
caption_extension = ".txt"
shuffle_keep_tokens = 1

# もし dataset.subset に同名オプションの記述があった場合にはそちらが優先される
[[dataset]]
resolution = 512
batch_size = 4
shuffle_keep_tokens = 2

  [[dataset.subset]]
  image_dir = "C:\\hoge"
  # このサブセットは shuffle_keep_tokens = 2 （所属する dataset の値が使われる）

  [[dataset.subset]]
  image_dir = "C:\\fuga"
  shuffle_keep_tokens = 3

  [[dataset.subset]]
  is_reg = true
  image_dir = "C:\\reg"
  shuffle_keep_tokens = 1

[[dataset]]
resolution = 768
batch_size = 2

  [[dataset.subset]]
  image_dir = "C:\\piyo"
  # このサブセットは shuffle_keep_tokens = 1 （general の値が使われる）
